# Generated by Django 3.0.8 on 2021-01-11 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_mydemo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mydemo',
        ),
    ]
