# Generated by Django 3.0.8 on 2021-01-11 16:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('account', '0003_delete_mydemo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zipcode', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('pant_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.Pant')),
                ('shirt_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.Shirt')),
                ('shoe_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.Shoe')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
    ]
